Added greedy and it's tests
graphprocessing/graph_coarsening pull request #109
Opened 2019-08-17 16:03 UTC by XEverentX

2019-08-17 17:49 UTC, allnes approved these changes

2019-08-17 18:36 UTC, aobolensk requested changes

2019-08-17 18:36 UTC, gooddoog commented on tests/source/greedy_test.cpp
> +    Matching ans = LAM(graph);
Why tests for Greedy algorithm launch LAM function?

2019-08-18 13:37 UTC, XEverentX commented on tests/source/greedy_test.cpp
> +    Matching ans = LAM(graph);
Логичное замечание :D
Сейчас попрвлю

2019-08-18 19:10 UTC, aobolensk approved these changes

2019-08-18 21:35 UTC, merged