add pga and parametric tests
graphprocessing/graph_coarsening pull request #76
Opened 2019-03-28 20:40 UTC by lordoz234

2019-03-28 21:51 UTC, allnes approved these changes

2019-03-29 18:48 UTC, aobolensk approved these changes

2019-03-30 19:12 UTC, lordoz234 commented
fix #69

2019-03-31 18:47 UTC, allnes commented
объедините с реквестом [https://github.com/graphprocessing/graph_coarsening/pull/79](https://github.com/graphprocessing/graph_coarsening/pull/79), у вас просто в 79 реквесте тот же код + max weighted matching

2019-04-09 16:01 UTC, allnes commented
добавьте пожалуйста проверки на max weighted matching

2019-04-10 20:08 UTC, aobolensk requested changes

2019-04-10 20:08 UTC, gooddoog commented on tests/include/pga_parametric_test.h
> +#include "../../modules/pch/include/precomp.h"
Precompiled header должен быть первым в списке.
#include <gtest/gtest.h> придется заменить на #include "gtest/gtest.h", чтобы cpplint не ругался

2019-04-21 12:19 UTC, gooddoog commented
Нужно добавить в описание fix #80

2019-04-21 12:27 UTC, gooddoog commented
Думаю, можно делать merge

2019-04-21 19:53 UTC, allnes approved these changes

2019-04-21 19:53 UTC, merged